services: 
  llm:
    image: ollama/ollama
    container_name: llm
    stop_grace_period: 1s
    labels:
      - "project=${PROJECT}"
    ports:
      - "11434:11434"
    networks:
      - network
    volumes:
      - models:/root/.ollama
      - shop:/code
    #devices:
    #  - /dev/dri
    #environment:
    #  - OLLAMA_VULKAN=1
    restart: unless-stopped
  agent:
    image: baer:latest
    container_name: agent
    user: "${UID}:${GID}"
    stop_grace_period: 1s
    labels:
      - "project=${PROJECT}"
    depends_on:
      - llm
    networks:
      - network
    volumes:
     - shop:/project:cached

volumes:
  models:
    labels:
     - "project=${PROJECT}"